free_parameters:
  - r
  - h
  - f
  - pxy
  - x0
  - y0
  - theta_x
  - theta_z
  - origin_x
  - origin_y

init_parameter_values:
  r: 6300000 # earth radius
  h: 418000 # ISS altitude
  f: 0.035 # 35mm
  px: 0.00001
  py: 0.00001
  x0: 0
  y0: 0
  theta_x: -3.141592653589793 # so that -y points toward planet center
  theta_y: 0
  theta_z: 0
  origin_x: 0
  origin_y: 1000000
  origin_z: 0

parameter_limits:
  r: [1000000.0, 10000000.0]
  h: [417000, 419000]
  f: [0.0, 1]
  px: [0.00001, 1]
  py: [0.00001, 1]
  x0: [-.inf, .inf]
  y0: [-.inf, .inf]
  theta_x: [-3.141592653589793, 3.141592653589793]
  theta_y: [0, 0]
  theta_z: [-3.141592653589793, 3.141592653589793]
  origin_x: [-.inf, .inf]
  origin_y: [-.inf, .inf]
  origin_z: [-.inf, .inf]

# "Normal" type accepts [std, mean] w/ default of above initialization
# "Uniform" type accepts [bounds=[lower, upper]] w/ default of above limits
parameter_priors:
  r:
    type: Normal
    std: 1000000
  h:
    type: Normal
    std: 1000
  f:
    type: Normal
    std: 0.005
  px:
    type: Uniform
    lower: 0.00001
    upper: 1
  py:
    type: Uniform
    lower: 0.00001
    upper: 1
  x0:
    type: Uniform
    lower: -1
    upper: 1
  y0:
    type: Uniform
    lower: -1
    upper: 1
  theta_x:
    type: Uniform
    lower: -3.141592653589793
    upper: 3.141592653589793
  theta_y:
    type: Uniform
    lower: -3.141592653589793
    upper: 3.141592653589793
  theta_z:
    type: Uniform
    lower: -3.141592653589793
    upper: 3.141592653589793
  origin_x:
    type: Uniform
    lower: -1500000
    upper: 1500000
  origin_y:
    type: Uniform
    lower: -1500000
    upper: 1500000
  origin_z:
    type: Uniform
    lower: -1500000
    upper: 1500000
