free_parameters:
  - r
  - h
  - f
  - pxy
  - x0
  - y0
  - theta_x
  - theta_z
  - origin_x
  - origin_y

init_parameter_values:
  r: 1188300 # pluto radius
  h: 18000 # closest approach
  f: 0.075 # RALPH 75mm f/8.7
  pxy: 1.0e-05
  px: 1
  py: 1
  x0: 0
  y0: 0
  theta_x: -3.141592653589793 # so that -y points toward planet center
  theta_y: 0
  theta_z: 0
  origin_x: 0
  origin_y: 207612 # distance to pluto horizon from new horizons
  origin_z: 0

parameter_limits:
  r: [5.0e+05, 1.0e+07]
  h: [1.78e+04, 1.82e+04]
  f: [0.0749, 0.0751]
  pxy: [1.0e-05, 1.0e+03]
  px: [1.0e-05, 1]
  py: [1.0e-05, 1]
  x0: [-1, 1]
  y0: [-1, 1]
  theta_x: [-3.141592653589793, 3.141592653589793]
  theta_y: [0, 0]
  theta_z: [-3.141592653589793, 3.141592653589793]
  origin_x: [-3.0e+05, 1.0e+06]
  origin_y: [-3.0e+05, 1.0e+06]
  origin_z: [-3.0e+05, 1.0e+06]
