free_parameters:
  - r
  - h
  - f
  - fov
  - theta_x
  - theta_y
  - theta_z

init_parameter_values:
  r: 750000
  h: 18000000 # https://photojournal.jpl.nasa.gov/catalog/PIA19948
  f: 0.6575 # RALPH/MVIC https://www.dpreview.com/articles/5293237047/nasa-new-horizons-probe-cameras-ralph
  fov: 5.7
  num_sample: 5000
  theta_x: -1.5088430066577383
  theta_y: 0
  theta_z: 0

parameter_limits:
  r: [6.0e+05, 1.9e+06]
  h: [1.0e+07, 2.4e+07]
  f: [0.650, 0.665]
  fov: [5.64, 5.76]
  num_sample: [4000, 6000]
  theta_x: [-3.14, 3.14]
  theta_y: [-3.14, 3.14]
  theta_z: [-3.14, 3.14]
