free_parameters:
  - r
  - h
  - f
  - py
  - y0
  - theta_x
  - theta_z
  - origin_y

init_parameter_values:
  r: 60268000 # saturn radius
  h: 1.2e+06 # cassini altitude
  f: 2.00270 # near-angle camera (NAC)
  px: 0.00001
  py: 0.00001
  x0: 0
  y0: 0
  theta_x: -3.141592653589793 # so that -y points toward planet center
  theta_y: 0
  theta_z: 0
  origin_x: 0
  origin_y: 24172976 # distance to saturn horizon from cassini
  origin_z: 0

parameter_limits:
  r: [1.0e+07, 1.0e+09]
  h: [1.1e+06, 1.3e+06]
  f: [2.001, 2.003]
  px: [1.0e-05, 1]
  py: [1.0e-05, 1]
  x0: [-1, 1]
  y0: [-1, 1]
  theta_x: [-3.141592653589793, 3.141592653589793]
  theta_y: [0, 0]
  theta_z: [-3.141592653589793, 3.141592653589793]
  origin_x: [-1.5e+06, 1.5e+06]
  origin_y: [-1.5e+06, 1.5e+06]
  origin_z: [-1.5e+06, 1.5e+06]
