free_parameters:
  - r
  - h
  - f
  - fov
  - theta_x
  - theta_y
  - theta_z

init_parameter_values:
  r: 75000000
  h: 1.2e+09 # cassini altitude https://photojournal.jpl.nasa.gov/catalog/PIA21341
  f: 2.00270 # narrow-angle camera (NAC) f/10.5asa-new-horizons-probe-cameras-ralph
  fov: 0.35 # https://ciclops.org/iss/iss.php.html
  num_sample: 5000
  theta_x: -1.5244989761883725
  theta_y: 0
  theta_z: 0

parameter_limits:
  r: [1.0e+07, 1.0e+08]
  h: [1.0e+09, 1.4e+09]
  f: [2.002, 2.003]
  fov: [0.34, 0.36]
  num_sample: [4000, 6000]
  theta_x: [-3.14, 3.14]
  theta_y: [-3.14, 3.14]
  theta_z: [-3.14, 3.14]
